#!/bin/bash

rootpath=/project/6007967/nhiebert

#use absolute paths here:
src=$rootpath/surf_striatum/
in=$rootpath/surf_striatum_rawdata/
out=$rootpath/surf_striatum_ouput/

subjlist=$src/subjlist


SINGULARITY_IMG=`shub-cache shub://akhanf/vasst-dev:v0.0.4c`



#use opts to set options for ALL jobs below
opts=""

#uncomment below for subjlist
#opts="$opts -s LCT15_1OFF"

#uncomment below for test mode (no submit jobs)
#opts="$opts -t"



#preproc & QC gen
#job2=$(neurogliaBatch ./2.0_processT1 $subjlist $opts -b $out  -j Short)
job3=$(neurogliaBatch ./3_genQC $subjlist $opts -b $out  -g -j Short)



# faillist is created after manual QC of affine reg, and init subject is 
# chosen to be one of the subj that did not fail
#faillist=./subjects_newJune2017.failReg
#init_subj=LPD16_1OFF

#preproc & QC gen 
#job2redo=$(neurogliaBatch ./2.1_processT1_regFail $faillist $opts -b $init_subj -d afterok:$job3 -j Short)
#job3redo=$(neurogliaBatch ./3_genQC $subjlist $opts -d afterok:$job2redo -g -j Short)

#volume-based diffusion tracking:
job41=$(neurogliaBatch ./4.1_genParcellation  $subjlist $opts -b $out  )
job42=$(neurogliaBatch ./4.2_warpParcellationsToMNI  $subjlist $opts -b $out -d aftercorr:$job41 -j Short)
job71=$(neurogliaBatch ./7.1_computeIndivParcMapLeftRight $subjlist $opts -b $out -d aftercorr:$job42 -j Short)
#job83=$(neurogliaBatch ./8.3_computeMaxProbDiffParcVolumeLeftRight $subjlist $opts -d afterok:$job71 -g )

exit 0


#surface-based morphometry & tracking:
job90=$(neurogliaBatch ./9.0_runSurfDisplacementTemplate  $subjlist $opts -d afterok:$job3redo -g -j Short)
job91=$(neurogliaBatch ./9.1_runSurfDisplacementTargets $subjlist $opts  -d afterok:$job90 )
job92=$(neurogliaBatch ./9.2_runSurfBasedTractography $subjlist $opts  -d afterok:$job91:$job4 )

#run matlab job to summarize surface-based displacement & tract data, and generate vtk files (visualize in paraview)
job93=$(neurogliaBatch ./9.3_analyzeSurfData $subjlist $opts -d afterok:$job92 -g )



