#!/bin/bash

#note: does not overwrite existing files!
#dependencies: dcm2niix, fsl

input_dir=$1
shift 1


for subj in $@
do

dti_dir=$input_dir/$subj/dti
t1_dir=$input_dir/$subj/t1



 echo $subj, $dti_dir

 if [ ! -e $subj/dwi/uncorrected/dwi.nii.gz ]
 then
   importDicomDTI_dcm2nii $dti_dir $subj
 fi

 if [ ! -e $subj/t1/t1.nii.gz ]
then
  importDicomT1 $t1_dir $subj
fi

done
